services:
  - type: web
    name: mediabotbackend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: SMTP_HOST
        value: smtp-relay.brevo.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: a2c5e2001@smtp-brevo.com
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: "MediaBot <kripaverma410@gmail.com>"
      - key: JWT_SECRET
        generateValue: true
